# NumPy Practice


In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
mat1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
mat2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
mat3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
mat1.shape, mat2.shape, mat3.shape

((3,), (2, 3), (2, 2, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
mat1.shape, mat1.dtype, mat1.size

((3,), dtype('int32'), 3)

In [4]:
# Attributes of 2-dimensional array
mat2.shape, mat2.dtype, mat2.size

((2, 3), dtype('int32'), 6)

In [5]:
# Attributes of 3-dimensional array
mat3.shape, mat3.dtype, mat3.size

((2, 2, 3), dtype('int32'), 12)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(mat2, columns=['A', 'B', 'C'])
df

A  B  C
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10,2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr = np.zeros((7,2,3))
zeros_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
step3_arr = np.arange(0, 100, 3)
step3_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.seed(42)
np.random.randint(0, 10, (7,2))

array([[6, 3],
       [7, 4],
       [6, 9],
       [2, 6],
       [7, 4],
       [3, 7],
       [7, 2]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomFloatArr = np.random.rand(3,5)
randomFloatArr

array([[0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Ans:The same numbers are generated every time you run the cell.

Are the numbers in the array different or the same? Why do think this is?

Ans:The numbers in the array are the same each time. Because setting np.random.seed(42) fixes the random generator, so the same numbers are produced every time.

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_arr = np.random.randint(1, 10, (3,7))

# Find the unique numbers in the array you just created
random_arr

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [14]:
# Find the 0'th index of the latest array you created
random_arr[0][0]

9

In [15]:
# Get the first 2 rows of latest array you created
random_arr[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr_new = np.random.randint(0, 10, (3,5))
ones_arr_new = np.ones((3,5))

In [18]:
# Add the two arrays together
sum = random_arr_new + ones_arr_new
sum

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [30]:
# Create another array of ones of shape (5, 3)
ones_arr_new2 = np.ones((5,3))
ones_arr_new2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# Try add the array of ones and the other most recent array together
sum += ones_arr_new2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

Ans: The error occurs because the two arrays have different shapes (3,5) and (5,3), so they cannot be added directly.

How would you fix it?

Ans: It can be fixed by transposing ones_arr_new2 using .T so both arrays have the same shape

In [29]:
# Create another array of ones of shape (3, 5)
another_ones_arr = np.ones((3,5))
another_ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
# Subtract the new array of ones from the other most recent array
sum -= another_ones_arr
sum

array([[ 9., 10.,  5.,  3.,  6.],
       [ 4., 10.,  6.,  4.,  8.],
       [ 8., 12.,  6.,  8.,  4.]])

In [35]:
# Multiply the ones array with the latest array
mult = another_ones_arr * sum
mult

array([[ 9., 10.,  5.,  3.,  6.],
       [ 4., 10.,  6.,  4.,  8.],
       [ 8., 12.,  6.,  8.,  4.]])

In [36]:
# Take the latest array to the power of 2 using '**'
mult ** 2

array([[ 81., 100.,  25.,   9.,  36.],
       [ 16., 100.,  36.,  16.,  64.],
       [ 64., 144.,  36.,  64.,  16.]])

In [37]:
# Do the same thing with np.square()
np.square(mult)

array([[ 81., 100.,  25.,   9.,  36.],
       [ 16., 100.,  36.,  16.,  64.],
       [ 64., 144.,  36.,  64.,  16.]])

In [38]:
# Find the mean of the latest array using np.mean()
np.mean(mult)

6.866666666666666

In [39]:
# Find the maximum of the latest array using np.max()
np.max(mult)

12.0

In [40]:
# Find the minimum of the latest array using np.min()
np.min(mult)

3.0

In [41]:
# Find the standard deviation of the latest array
np.std(mult)

2.578543947441829

In [42]:
# Find the variance of the latest array
np.var(mult)

6.648888888888889

In [43]:
# Reshape the latest array to (3, 5, 1)
np.reshape(mult, (3,5,1))

array([[[ 9.],
        [10.],
        [ 5.],
        [ 3.],
        [ 6.]],

       [[ 4.],
        [10.],
        [ 6.],
        [ 4.],
        [ 8.]],

       [[ 8.],
        [12.],
        [ 6.],
        [ 8.],
        [ 4.]]])

In [44]:
# Transpose the latest array
mult.T

array([[ 9.,  4.,  8.],
       [10., 10., 12.],
       [ 5.,  6.,  6.],
       [ 3.,  4.,  8.],
       [ 6.,  8.,  4.]])

What does the transpose do?
Ans: The transpose flips the rows and columns of an array — it converts the shape from (m, n) to (n, m).

In [47]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand1 = np.random.randint(0, 10, (3,3))
rand2 = np.random.randint(0, 10, (3,2))


In [48]:
# Perform a dot product on the two newest arrays you created
np.dot(rand1, rand2)

array([[114, 141],
       [106, 128],
       [ 49,  46]])

In [51]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand3 = np.random.randint(0, 10, (4,3))
rand4 = np.random.randint(0, 10, (4,3))

In [52]:
# Perform a dot product on the two newest arrays you created
np.dot(rand3, rand4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
Ans: The dot product fails because shapes don’t align; fix it by using np.dot(rand3, rand4.T).

In [50]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(rand3, rand4.T)

NameError: name 'rand3' is not defined

Notice how performing a transpose allows the dot product to happen.

Why is this?

Ans: Performing the transpose changes the second array’s shape so its number of rows matches the first array’s number of columns, making their dimensions compatible for matrix multiplication.
Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [53]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0, 10, (3,3))
arr2 = np.random.randint(0, 10, (3,3))
arr1

array([[2, 5, 1],
       [9, 8, 4],
       [5, 3, 9]])

In [54]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False, False, False],
       [ True,  True, False],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

Ans: Using `>` compares elements pairwise and returns a Boolean array showing where the first array’s values are greater than the second’s.

In [55]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[False, False, False],
       [ True,  True, False],
       [False,  True,  True]])

In [56]:
# Find which elements of the first array are greater than 7

mask = arr1 > 7
arr1[mask]

array([9, 8, 9])

In [57]:
# Which parts of each array are equal? (try using '==')
mask = arr1 == arr2
arr1[mask]

array([3])

In [59]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[1, 2, 5],
       [4, 8, 9],
       [3, 5, 9]])

In [60]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1, axis=1)

array([[2, 0, 1],
       [2, 1, 0],
       [1, 0, 2]], dtype=int64)

In [61]:
# Find the index with the maximum value in one of the arrays you've created
np.unravel_index(np.argmax(arr1), arr1.shape)

(1, 0)

In [62]:
# Find the index with the minimum value in one of the arrays you've created
np.unravel_index(np.argmin(arr1), arr1.shape)

(0, 2)

In [63]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)

array([1, 0, 2], dtype=int64)

In [64]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1, axis=0)

array([0, 2, 0], dtype=int64)

In [65]:
# Create an array of normally distributed random numbers
normal_distrib = np.random.randn(3,4)
normal_distrib

array([[-0.87030495, -0.50664322, -1.30995069,  2.94366342],
       [-1.0962658 ,  0.91488432, -0.66606062, -0.51378749],
       [ 0.3013228 , -1.45851692, -0.66273831, -0.14647281]])

In [66]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])